services:
  - type: web
    name: jevelon
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn jevelon_backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jevelon-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SENDGRID_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "jevelonemmisions@gmail.com"
      - key: ADMIN_EMAIL
        value: "jevelonemmisions@gmail.com"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://jevelon.vercel.app,https://jevelon.com"

databases:
  - name: jevelon-db
    databaseName: jevelon_db
    user: jevelon_user 